#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "book_management.h"

static struct Book *all_books=0;
static struct BookArray books_array;
static int number_books=0;
//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file){
  FILE* loaded_file= file;
  all_books= calloc(number_books,sizeof(struct Book));
  books_array.length=0;
  int buff=0;
  char b;
  char buff1[512];
  struct Book loaded_book;
  char *token;
  int i=0;

  for(b=getc(file);b!=EOF;b=getc(file)){
    if(b=='\n'){
      i++;
    }
  }
  rewind(file);

  number_books=i-1;
  while (fgets(buff1, 512, file)) {

    if(buff==0){
      buff++;
      continue;
    }
    //Title
    token= strtok(buff1,",");
    strcpy(loaded_book.title,token);

    //Author
    token= strtok(NULL,",");
    strcpy(loaded_book.authors,token);

    //Year
    token= strtok(NULL,",");
    loaded_book.year= atoi(token);

    //Copies
    token= strtok(NULL,",");
    loaded_book.copies= atoi(token);

    all_books[books_array.length]= loaded_book;
    number_books++;
    books_array.length++;
    }

  books_array.array= (struct Book*) all_books;


  return 0;
}
//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(struct Book book) {

  return -1;
}

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(struct Book book){
  return -1;
}

//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file){
  FILE* store_file=file;
  struct Book book_temp;
  const struct Book *array_temp=books_array.array;

  if(store_file==NULL){
    return -1;
  }
  all_books= calloc(number_books,sizeof(struct Book));

  for(int i=0; i<number_books;i++){
    fprintf(file, "%s","%s","%d","%d\n", array_temp->title, array_temp->authors, array_temp->year, array_temp->copies);
  }


  return 0;
}

//finds books with a given title.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray find_book_by_title (const char *title){
  struct BookArray empty;
  return empty;
}

//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray find_book_by_author (const char *author){
  struct BookArray empty;
  return empty;
}

//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray find_book_by_year (unsigned int year){
  struct BookArray empty;
  return empty;
}


int main(){
  FILE* file1= fopen("../books.csv","r");
  FILE* file2= fopen("../test_file.csv","a");

  load_books(file1);
  store_books(file2);

  return 0;
}
