#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "book_management.h"

static struct Book *all_books=0;
static struct BookArray books_array;
static int number_books=0;
//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file){
  books_array.length=0;
  int buff=0;
  char b;
  char buff1[512];
  struct Book* loaded_book;
  loaded_book= (struct Book*)malloc(sizeof(struct Book));
  char *token;
  int i=0;

  for(b=getc(file);b!=EOF;b=getc(file)){
    if(b=='\n'){
      i++;
    }
  }
  rewind(file);

  number_books=i-1;
  all_books= calloc(number_books,sizeof(struct Book));
  while (fgets(buff1, 512, file)) {

    if(buff==0){
      buff++;
      continue;
    }
    //Title
    token= strtok(buff1,",");
    loaded_book->title=(char*)malloc(sizeof(char)*strlen(token));
    strcpy(loaded_book->title,token);

    //Author
    token= strtok(NULL,",");
    loaded_book->authors=(char*)malloc(sizeof(char)*strlen(token));
    strcpy(loaded_book->authors,token);

    //Year
    token= strtok(NULL,",");
    loaded_book->year= atoi(token);

    //Copies
    token= strtok(NULL,",");
    loaded_book->copies= atoi(token);

    all_books[books_array.length]= *loaded_book;
    number_books++;
    books_array.length++;
    }

  books_array.array= (struct Book*) all_books;


  return 0;
}
//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(struct Book book) {
  /*struct Book* temp_array=(struct Book*)malloc((sizeof(struct Book*)*books_array.length)+1); //creates extra space in the array for the new book.

  int i;
  for(i=0;i<books_array.length; i++){
    if(books_array.array[i].title!=book.title && books_array.array[i].authors!=book.authors
      && books_array.array[i].year!=book.year && books_array.array[i].copies!=book.copies){
      return 1;
    }
  }

  temp_array[i].title=books_array.array[i].title;
  temp_array[i].authors=books_array.array[i].authors;
  temp_array[i].year=books_array.array[i].year;
  temp_array[i].copies=books_array.array[i].copies;

  book = temp_array[i+1];
  memcpy(books_array.array,temp_array,sizeof(struct Book));*/
  books_array.array[books_array.length]= book;
  books_array.length++;
  number_books++;
  return 0;
}

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(struct Book book){
/*  int i=0;
  int x=0,

  for(;x<number_books;x++){
    if(books_array.array[i])
  }

  else{
    for(;i<NumberBookings;i++){
      if(BookingsTable[i][0]==booking_number){
          cancelSeatReservation(booking_number);
          NumberBookings--;
        }

      else if(BookingsTable[i][0]>=booking_number){
        for(;i<26;i++){
            int x=i-1;
            BookingsTable[x][0]=BookingsTable[i][0];
            BookingsTable[x][1]=BookingsTable[i][1];
            BookingsTable[x][2]=BookingsTable[i][2];
            BookingsTable[x][3]=BookingsTable[i][3];
          }
      }
    }
  return 1;*/
}

//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file){
  struct Book book_temp;
  struct Book* array_temp= (struct Book*)malloc(sizeof(struct Book*));
  array_temp=books_array.array;
  //array_temp=all_books;

  if(file==NULL){
    return -1;
  }
  //all_books= calloc(number_books,sizeof(struct Book));

  for(int i=0; i<books_array.length;i++){
    book_temp= *(array_temp+i);
    fprintf(file, "%s,%s,%d,%d\n", book_temp.title, book_temp.authors, book_temp.year, book_temp.copies);
  }
  return 0;
}

//finds books with a given title.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray find_book_by_title (const char *title){
  struct BookArray empty;
  return empty;
}

//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray find_book_by_author (const char *author){
  struct BookArray empty;
  return empty;
}

//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray find_book_by_year (unsigned int year){
  struct BookArray empty;
  return empty;
}

/*
int main(){
  FILE* file1= fopen("../books.csv","r");
  FILE* file2= fopen("../test_file.csv","a");

  struct Book b;
  b.title = "Bible";
  b.authors="Jesus Christ";
  b.year=1234;
  b.copies=6;
  load_books(file1);
  add_book(b);
  store_books(file2);

  return 0;
}*/
