#ifndef LIBRARY_GUARD_H
#define LIBRARY_GUARD_H

#include <string.h>
#include "book_management.h"
#include "users.h"


typedef struct{
    unsigned int loan_id;
    unsigned int user_id;
    unsigned int book_id;
}Loan;

typedef struct{
  Loan* array;
  unsigned int length;
}LoanArray;

LoanArray loans_array;
int number_loans;
//loads the database of loans from the specified file
//the file must have been generated by a previous call to store_loans()
//returns 0 if loans were loaded correctly, or an error code otherwise
int load_loans(FILE *file);

//Cheks if the provided book has enough copies left in the library's database.
//Returns 0 if the book is available and 1 otherwise.
int is_available(struct Book book);

//Removes the specified book from the library's database while decreasing the number of available copies and
//adds it to the user's books_borrowed array and returns 0 if successful;
const int borrow_book(struct Book b, User u);

//Removes the specified book from the user'books_borrowed array and
//adds it to the library's books database while increasing the number of available copies and returns 0 if successful;
const int return_book(struct Book b, User u);

//saves the database of loans in the specified file
//returns 0 if loans were stored correctly, or an error code otherwise
int store_loans(FILE *file);

#endif
